CREATE FUNCTION DBO.MALZEME_AYLIKSATIS(@MALZEMEKODU AS VARCHAR(20),@AYNO AS INTEGER)
RETURNS FLOAT
AS
BEGIN
	DECLARE @SONUC AS FLOAT
	SELECT @SONUC=(SELECT SUM(TUTAR) FROM VW_SATISLAR WHERE MALZEMEKODU=@MALZEMEKODU AND DATEPART(MONTH,TARIH)=@AYNO)
	RETURN @SONUC
END

SELECT dbo.MALZEME_AYLIKSATIS('8583',3)