CREATE FUNCTION DBO.AYADI(@TARIH AS DATETIME)
RETURNS VARCHAR(20)
AS
BEGIN
	DECLARE @AYADI AS VARCHAR(20) 
	IF DATEPART(MONTH,@TARIH)=1 SET @AYADI='01.OCAK'
	IF DATEPART(MONTH,@TARIH)=2 SET @AYADI='02.ÞUBAT'
	IF DATEPART(MONTH,@TARIH)=3 SET @AYADI='03.MART'
	IF DATEPART(MONTH,@TARIH)=4 SET @AYADI='04.NÝSAN'
	IF DATEPART(MONTH,@TARIH)=5 SET @AYADI='05.MAYIS'
	IF DATEPART(MONTH,@TARIH)=6 SET @AYADI='06.HAZÝRAN'
	IF DATEPART(MONTH,@TARIH)=7 SET @AYADI='07.TEMMUZ'
	IF DATEPART(MONTH,@TARIH)=8 SET @AYADI='08.AÐUSTOS'
	IF DATEPART(MONTH,@TARIH)=9 SET @AYADI='09.EYLÜL'
	IF DATEPART(MONTH,@TARIH)=10 SET @AYADI='10.EKÝM'
	IF DATEPART(MONTH,@TARIH)=11 SET @AYADI='11.KASIM'
	IF DATEPART(MONTH,@TARIH)=12 SET @AYADI='12.ARALIK'
RETURN @AYADI
END