SELECT TOP 10000
dbo.MALZEME_AYLIKSATIS(MALZEMEKODU,DATEPART(MONTH,TARIH)),
TUTAR/dbo.MALZEME_AYLIKSATIS(MALZEMEKODU,DATEPART(MONTH,TARIH))*100 AS YUZDE,
dbo.AYADI(TARIH) AS AYADI,TUTAR,
* 
FROM VW_SATISLAR
WHERE MALZEMEKODU LIKE '85%'
ORDER BY 3